apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio
  namespace: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
