apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "66.2.*"
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: monitoring
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    admin:
      existingSecret: grafana-login-secret
      userKey: admin-user
      passwordKey: admin-password
    grafana:
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grs.ml.lab
        tls:
          - secretName: grafana-tls-secret
            hosts:
              - grs.ml.lab
          
