apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http-web
      port: 8080
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer

